Add new tables and relationships to model animals and owners
Oscar-Espinoza/vet_clinic pull request #4
Opened 2023-03-01 17:36 UTC by Oscar-Espinoza

This PR adds new tables and relationships to the existing "animals" table to better model the one-to-many relationships between animals and their owners, as well as between animals and their species. The changes are as follows:

- Added a new table "owners" with columns "id", "full_name", and "age"
- Added a new table "species" with columns "id" and "name"
- Modified the existing "animals" table by removing the "species" column and adding the "species_id" and "owner_id" columns, which are foreign keys that reference the "species" and "owners" tables respectively
- The PR also includes sample data for the new tables and updated data for the "animals" table to include the new foreign key values.

Additionally, the PR includes a new query file "queries.sql" with queries that answer the following questions:

- What animals belong to Melody Pond?
- List of all animals that are pokemon (their type is Pokemon).
- List all owners and their animals, remember to include those that don't own any animal.
- How many animals are there per species?
- List all Digimon owned by Jennifer Orwell.
- List all animals owned by Dean Winchester that haven't tried to escape.
- Who owns the most animals?

The PR has been tested locally and all queries are returning the expected results. Please review and merge at your earliest convenience.

![q_1](https://user-images.githubusercontent.com/37676636/222218003-cb716663-1e70-481a-a665-af3d33b84815.png)
![q_2](https://user-images.githubusercontent.com/37676636/222218007-9314ab77-1391-4bda-98d4-c241bf250eb0.png)

Thank you!

2023-03-01 19:15 UTC, mckent05 requested changes
Hi @Oscar-Espinoza, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- You did well adding new tables to your database 👏 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-01 19:15 UTC, mckent05 commented on schema.sql
> +);
- Since there is a `species` table, according to the project requirements, the `species` column in the animals' table should be dropped. I expect to see a line of code performing the said action, Please fix this 🙏

2023-03-01 19:15 UTC, mckent05 commented on data.sql
> +  ('Angemon', '2015-07-20', 3, false, 18.5, 2, 5),
- Good job done so far, but there are some alterations to the `animals` table that are missing in your `data.sql` file. Please make sure all modifications in the [project requirements](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_query_multiple_tables.md) have been met and reflect in your `data.sql` file. Please fix this 👍 👍

2023-03-01 19:15 UTC, mckent05 commented on queries.sql
> +ORDER BY owners.id;
- Good job done so far, in total there should be 7 queries in your `data.sql` file for this milestone, but you have only three, please add the remaining queries and attach screenshots of your results in the PR report summary. Please fix this 🙏

2023-03-01 19:15 UTC, mckent05 commented on queries.sql
> +SELECT animals.name FROM animals JOIN species ON animals.species_id = species.id WHERE species.name = 'Pokemon';
- Good job done o far, but from your screenshots, the result attached for this query is incorrect, there are 4 animals belonging to the `Pokemon` species, and from your result I see 5. Please fix this 🙏

2023-03-02 16:24 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🍾✔🎉**
Hello @Oscar-Espinoza 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- You asked for the changes in a polite and friendly way.
- Your linters are passing all the checks.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-02 17:19 UTC, merged